services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    expose:
      - 2181
    volumes:
      - ./zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tiny-url-network
  cassandra:
    image: "bitnami/cassandra:latest"
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
    expose:
      - 9042
    volumes:
      - ./cassandra_data:/bitnami
    networks:
      - tiny-url-network
  backend:
    build:
      context: apps/backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    expose:
      - 5000
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    env_file: apps/backend/.env
    depends_on:
      - cassandra
      - zookeeper
    networks:
      - tiny-url-network
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - tiny-url-network

networks:
  tiny-url-network:
    driver: bridge