services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - ./zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  cassandra:
    image: 'bitnami/cassandra:latest'
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
    ports:
      - '9042:9042'
    volumes:
      - ./cassandra_data:/bitnami
  backend:
    build:
      context: apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    env_file: apps/backend/.env
    depends_on:
      - cassandra
      - zookeeper